Repository ansible-collections/junipernetworks.junos, pull requests merged in 2022-04, with the labels that each got.

#293 Junos ACLs facts gathering firewall config fix
  changelogs/fragments/fix_acl_facts_gathering_issue.yml
  docs/junipernetworks.junos.junos_acls_module.rst
  plugins/module_utils/network/junos/argspec/acls/acls.py
  plugins/module_utils/network/junos/config/acls/acls.py
  plugins/module_utils/network/junos/facts/acls/acls.py
  plugins/modules/junos_acls.py
  tests/integration/targets/junos_acls/tests/netconf/empty_config.yaml
  tests/integration/targets/junos_acls/tests/netconf/fixtures/parsed.cfg
  tests/integration/targets/junos_acls/tests/netconf/parsed.yaml
  tests/integration/targets/junos_acls/tests/netconf/rendered.yaml
Labels: mergeit

#295 Sanity tests: copy ignore-2.13.txt to ignore-2.14.txt
  changelogs/fragments/0-ignore.yml
  tests/sanity/ignore-2.14.txt
Labels: mergeit

#300 Junos: Add fqcn to ansible_connection to support stable-2.9
  changelogs/fragments/add_fqcn_ansible_connection.yaml
  tests/integration/targets/junos_smoke/tasks/cli.yaml
  tests/integration/targets/junos_smoke/tests/cli/caching.yaml
Labels: blocks_release

#298 Junos Facts: change default subset to min
  changelogs/fragments/junos_facts.yaml
  docs/junipernetworks.junos.junos_facts_module.rst
  plugins/module_utils/network/junos/argspec/facts/facts.py
  plugins/modules/junos_facts.py
  tests/integration/targets/junos_facts/tests/netconf/facts.yaml
  tests/unit/modules/network/junos/test_junos_facts.py
Labels: blocks_release, mergeit

#275 updated references of base plugins to netcommon
  changelogs/fragments/netcommon_ref_update.yaml
  galaxy.yml
  plugins/cliconf/junos.py
  plugins/netconf/junos.py
  plugins/terminal/junos.py
Labels: blocks_release, mergeit

#302 Prepare release 3.0.0
  CHANGELOG.rst
  README.md
  changelogs/changelog.yaml
  changelogs/fragments/0-ignore.yml
  changelogs/fragments/add_fqcn_ansible_connection.yaml
  changelogs/fragments/fix_acl_facts_gathering_issue.yml
  changelogs/fragments/junos_facts.yaml
  changelogs/fragments/netcommon_ref_update.yaml
  changelogs/fragments/runtime_fix.yml
  docs/junipernetworks.junos.junos_cliconf.rst
  docs/junipernetworks.junos.junos_security_policies_global_module.rst
  docs/junipernetworks.junos.junos_security_policies_module.rst
  docs/junipernetworks.junos.junos_security_zones_module.rst
Labels: mergeit
