Repository ansible-collections/junipernetworks.junos, pull requests merged in 2023-08, with the labels that each got.

#430 Add Overridden operation support
  .github/workflows/release.yml
  changelogs/fragments/overridden_support.yaml
  docs/junipernetworks.junos.junos_bgp_global_module.rst
  docs/junipernetworks.junos.junos_ospf_interfaces_module.rst
  plugins/module_utils/network/junos/argspec/bgp_global/bgp_global.py
  plugins/module_utils/network/junos/argspec/ospf_interfaces/ospf_interfaces.py
  plugins/module_utils/network/junos/config/bgp_global/bgp_global.py
  plugins/module_utils/network/junos/config/ospf_interfaces/ospf_interfaces.py
  plugins/module_utils/network/junos/facts/ospf_interfaces/ospf_interfaces.py
  plugins/modules/junos_bgp_global.py
  plugins/modules/junos_ospf_interfaces.py
  tests/integration/targets/junos_bgp_global/tests/netconf/overridden.yaml
  tests/integration/targets/junos_ospf_interfaces/tests/netconf/merged.yaml
  tests/integration/targets/junos_smoke/tasks/cli.yaml
  tests/unit/mock/loader.py
Labels: enhancement

#434 Update BGP tests
  changelogs/fragments/bgp_global_tests_fix.yaml
  tests/integration/targets/junos_bgp_global/vars/main.yaml
Labels: bug

#438 Added new codecov workflow
  changelogs/fragments/codecov_pr.yml
  codecov.yml
Labels: skip-changelog
