Repository ansible-collections/junipernetworks.junos, pull requests merged in 2024-01, with the labels that each got.

#488 Fixes module_defaults being incorrectly applied to platform actions
  changelogs/fragments/module_defaults.yaml
  meta/runtime.yml
Labels: bug

#490 Add symlinks to junos action
  plugins/action/acl_interfaces.py
  plugins/action/acls.py
  plugins/action/banner.py
  plugins/action/bgp_address_family.py
  plugins/action/bgp_global.py
  plugins/action/command.py
  plugins/action/config.py
  plugins/action/facts.py
  plugins/action/hostname.py
  plugins/action/interfaces.py
  plugins/action/l2_interfaces.py
  plugins/action/l3_intefaces.py
  plugins/action/lacp.py
  plugins/action/lacp_intefaces.py
  plugins/action/lag_interfaces.py
  plugins/action/lldp_global.py
  plugins/action/lldp_interfaces.py
  plugins/action/logging.py
  plugins/action/logging_global.py
  plugins/action/netconf.py
  plugins/action/ntp_global.py
  plugins/action/ospf_interfaces.py
  plugins/action/ospfv2.py
  plugins/action/ospfv3.py
  plugins/action/package.py
  plugins/action/ping.py
  plugins/action/prefix_lists.py
  plugins/action/routing_instances.py
  plugins/action/routing_options.py
  plugins/action/rpc.py
  plugins/action/scp.py
  plugins/action/security_policies.py
  plugins/action/security_policies_global.py
  plugins/action/security_zones.py
  plugins/action/snmp_server.py
  plugins/action/static_routes.py
  plugins/action/system.py
  plugins/action/user.py
  plugins/action/vlans.py
  plugins/action/vrf.py
Labels: bug, skip-changelog

#491 update requirements
  .pre-commit-config.yaml
  plugins/module_utils/network/junos/facts/security_policies/security_policies.py
  plugins/module_utils/network/junos/facts/security_zones/security_zones.py
  test-requirements.txt
Labels: skip-changelog

#492 Prepare Release
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/module_defaults.yaml
  changelogs/fragments/trivial_lint.yaml
Labels: skip-changelog
