Repository ansible-collections/junipernetworks.junos, pull requests merged in 2024-06, with the labels that each got.

#518 Update galaxy.yml
  galaxy.yml
Labels: skip-changelog

#517 Prepare release v9.0.0
  CHANGELOG.rst
  changelogs/changelog.yaml
  changelogs/fragments/bump_to_215.yaml
Labels: skip-changelog

#519 Content action workflow fix for release
  .github/workflows/release.yml
Labels: skip-changelog

#526 [CI] maintenance updates
  .pre-commit-config.yaml
  plugins/module_utils/network/junos/facts/security_policies/security_policies.py
  plugins/module_utils/network/junos/facts/security_zones/security_zones.py
  test-requirements.txt
  tests/unit/plugins/terminal/test_junos.py
Labels: skip-changelog

#522 Add MTU support for L3 interfaces
  changelogs/fragments/support_l3_mtu.yaml
  docs/junipernetworks.junos.junos_l3_interfaces_module.rst
  plugins/module_utils/network/junos/argspec/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/junos/config/l3_interfaces/l3_interfaces.py
  plugins/module_utils/network/junos/facts/l3_interfaces/l3_interfaces.py
  plugins/modules/junos_l3_interfaces.py
  tests/integration/targets/junos_l3_interfaces/tests/netconf/fixtures/parsed.cfg
  tests/integration/targets/junos_l3_interfaces/tests/netconf/junos_l3_interfaces.yml
  tests/integration/targets/junos_l3_interfaces/tests/netconf/parsed.yaml
Labels: bug

#525 implement facts gathering and config for lag interface members.
  changelogs/fragments/add_support_for_gig_ether_lag.yaml
  docs/junipernetworks.junos.junos_lag_interfaces_module.rst
  plugins/module_utils/network/junos/argspec/lag_interfaces/lag_interfaces.py
  plugins/module_utils/network/junos/config/lag_interfaces/lag_interfaces.py
  plugins/module_utils/network/junos/facts/lag_interfaces/lag_interfaces.py
  plugins/modules/junos_lag_interfaces.py
  tests/integration/targets/junos_lag_interfaces/tests/netconf/fixtures/parsed.cfg
  tests/integration/targets/junos_lag_interfaces/tests/netconf/parsed.yaml
Labels: enhancement

#515 implement bridge domains and add support for virtual-switch
  changelogs/fragments/implement_bridge_domains.yaml
  docs/junipernetworks.junos.junos_routing_instances_module.rst
  plugins/module_utils/network/junos/argspec/routing_instances/routing_instances.py
  plugins/module_utils/network/junos/config/routing_instances/routing_instances.py
  plugins/module_utils/network/junos/facts/routing_instances/routing_instances.py
  plugins/modules/junos_routing_instances.py
  tests/unit/modules/network/junos/test_junos_routing_instances.py
Labels: routing_instances
